# Generated by Django 4.2.1 on 2026-07-06 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("OpenBench", "0003_sshcredential"),
    ]

    operations = [
        migrations.AddField(
            model_name="test",
            name="base_build_args",
            field=models.CharField(blank=True, default="", max_length=256),
        ),
        migrations.AddField(
            model_name="test",
            name="base_build_name",
            field=models.CharField(default="default", max_length=64),
        ),
        migrations.AddField(
            model_name="test",
            name="dev_build_args",
            field=models.CharField(blank=True, default="", max_length=256),
        ),
        migrations.AddField(
            model_name="test",
            name="dev_build_name",
            field=models.CharField(default="default", max_length=64),
        ),
    ]
