# Generated by Django 4.2.1 on 2026-07-06 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("OpenBench", "0004_test_base_build_args_test_base_build_name_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="test",
            name="base_build_args",
            field=models.CharField(blank=True, default="", max_length=512),
        ),
        migrations.AlterField(
            model_name="test",
            name="dev_build_args",
            field=models.CharField(blank=True, default="", max_length=512),
        ),
        migrations.CreateModel(
            name="BuildVariant",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("engine", models.CharField(max_length=64)),
                ("name", models.CharField(max_length=64)),
                ("args", models.CharField(max_length=512)),
                ("author", models.CharField(max_length=64)),
                ("created", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "unique_together": {("engine", "name")},
            },
        ),
    ]
