# Generated by Django 4.2.1 on 2026-07-06 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "OpenBench",
            "0005_alter_test_base_build_args_alter_test_dev_build_args_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="network",
            name="aux_sha256",
            field=models.CharField(blank=True, default="", max_length=8),
        ),
    ]
