# Generated by Django 4.2.1 on 2026-07-07 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("OpenBench", "0010_network_aux_files"),
    ]

    operations = [
        migrations.AddField(
            model_name="test",
            name="base_display",
            field=models.CharField(blank=True, default="", max_length=64),
        ),
        migrations.AddField(
            model_name="test",
            name="dev_display",
            field=models.CharField(blank=True, default="", max_length=64),
        ),
    ]
