# Generated by Django 4.2.1 on 2026-07-10 03:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("OpenBench", "0011_test_display_names"),
    ]

    operations = [
        migrations.CreateModel(
            name="TuneKit",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("engine", models.CharField(max_length=64)),
                ("name", models.CharField(max_length=64)),
                ("author", models.CharField(max_length=64)),
                ("tune_text", models.TextField()),
                ("params_text", models.TextField(blank=True, default="")),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("updated", models.DateTimeField(auto_now=True)),
            ],
            options={
                "unique_together": {("engine", "name")},
            },
        ),
    ]
