"""
Django settings for OpenSite project.

Generated by 'django-admin startproject' using Django 2.0.6.

For more information on this file, see
https://docs.djangoproject.com/en/2.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/2.0/ref/settings/
"""

import os

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

def env_bool(name, default):
    value = os.environ.get(name)
    if value is None:
        return default
    return value.strip().lower() in ('1', 'true', 'yes', 'on')

def env_list(name, default):
    value = os.environ.get(name)
    if value is None:
        return default
    return [x.strip() for x in value.split(',') if x.strip()]

# Production deployments must provide OPENBENCH_SECRET_KEY. The hardcoded
# key below is only ever used for local development, where DEBUG defaults
# to True. Setting OPENBENCH_SECRET_KEY flips DEBUG off unless overridden.
SECRET_KEY = os.environ.get(
    'OPENBENCH_SECRET_KEY',
    '@!zw2l8til1(0eb_nk+1w!(n78gqm&u)s)_v7#k6iseia@g9q0')

DEBUG = env_bool('OPENBENCH_DEBUG', 'OPENBENCH_SECRET_KEY' not in os.environ)

ALLOWED_HOSTS = env_list('OPENBENCH_ALLOWED_HOSTS', ['*'])

# Required when serving over HTTPS behind a proxy (Fly.io, Render, etc).
# Example: OPENBENCH_CSRF_TRUSTED_ORIGINS=https://shogibench.fly.dev
CSRF_TRUSTED_ORIGINS = env_list('OPENBENCH_CSRF_TRUSTED_ORIGINS', [])

if not DEBUG:
    SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')
    SESSION_COOKIE_SECURE   = True
    CSRF_COOKIE_SECURE      = True

# Public base URL of this server, embedded into worker connection snippets
# and SSH bootstraps. Must be the https:// URL workers should talk to; an
# http:// URL would get redirected and break the client's POST requests.
# Defaults to the first CSRF trusted origin.
PUBLIC_URL = os.environ.get(
    'OPENBENCH_PUBLIC_URL', CSRF_TRUSTED_ORIGINS[0] if CSRF_TRUSTED_ORIGINS else None)

# Writable directory for the SQLite database and /Media/ uploads. Point
# this at a persistent volume when deploying to a PaaS with ephemeral disks.
DATA_DIR = os.environ.get('OPENBENCH_DATA_DIR', BASE_DIR)
os.makedirs(DATA_DIR, exist_ok=True)

# Stream large uploads (Networks are 100-200MB) to the data volume, so the
# final save into /Media/ is a cheap same-filesystem rename
FILE_UPLOAD_TEMP_DIR = os.path.join(DATA_DIR, 'tmp')
os.makedirs(FILE_UPLOAD_TEMP_DIR, exist_ok=True)

HTML_MINIFY   = True
APPEND_SLASH  = True

DEFAULT_AUTO_FIELD = 'django.db.models.AutoField'

# Application definition

SETTINGS_DIR  = os.path.dirname(__file__)
PROJECT_PATH  = os.path.join(SETTINGS_DIR, os.pardir)
PROJECT_PATH  = os.path.abspath(PROJECT_PATH)
TEMPLATE_PATH = os.path.join(PROJECT_PATH, 'Templates')

MEDIA_URL  = '/Media/'
MEDIA_ROOT = os.path.join(DATA_DIR, 'Media')

INSTALLED_APPS = [
    'OpenBench',
    'OpenBench.templatetags',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'htmlmin.middleware.HtmlMinifyMiddleware',
    'htmlmin.middleware.MarkRequestMiddleware',
]

ROOT_URLCONF = 'OpenSite.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [TEMPLATE_PATH, ],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'django.template.context_processors.media',
            ],
        },
    },
]

WSGI_APPLICATION = 'OpenSite.wsgi.application'


# Database
# https://docs.djangoproject.com/en/2.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': os.path.join(DATA_DIR, 'db.sqlite3'),
    }
}


# Password validation
# https://docs.djangoproject.com/en/2.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/2.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/2.0/howto/static-files/

STATIC_URL  = '/static/'
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')

STORAGES = {
    'default': {
        'BACKEND': 'django.core.files.storage.FileSystemStorage',
    },
    'staticfiles': {
        'BACKEND': 'whitenoise.storage.CompressedStaticFilesStorage',
    },
}
